p8105_hw2_yl4924
================
Yongzheng Li
2022-10-05

# load the package

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

# Problem 1

### import and clean the data

``` r
trans_ent = 
  read_csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

The dataset contain 1868 rows and 9 cols. the dataset contain line,
station_name, station_latitude, station_lonitude, entry, vending,
entrance_type, and ada. For the data cleaning step, I convert from
route8 to rounte11 to become character variable. Then I clean the name
to be the same. I convert entry variable from char to logic. The data
are not tidy since there are multiple variables named from route1 to
route 11. We should transform these variable from wide to long format to
make it tidy.

### distinct station

``` r
trans_ent %>% 
  select(station_name, line) %>% 
  distinct()
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

there are total of 465 distinct station.

### stations are ADA compliant

``` r
trans_ent %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

from the dataframe, there are total 84 stations are ADA compliant.

### proportion of station entrances / exits without vending allow entrance

``` r
trans_ent %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

the proportion of station entrances/ exists without vending allow
entrance = 0.3770492

### distinct stations serve the A train

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

there are 60 stations serve the A train. Of the stations that serve the
A train, 17 are ADA compliant

# Problem 2

### Read and clean the Mr. Trash Wheel sheet

Variable ‘year’ in Mr. Trash Wheel is character variable. I decide to
convert year to numerical variable.

``` r
mr_trash <- read_excel("./data/Trash Wheel Collection Data.xlsx", range = "A2:N549", sheet = "Mr. Trash Wheel" ) %>% 
            janitor::clean_names() %>% 
            mutate(
              sports_balls = round(sports_balls),
              sports_balls = as.integer(sports_balls),
              year = as.numeric(year))
```

### Read and clean the Professor Trash Wheel sheet

``` r
professor_trash <- read_excel("./data/Trash Wheel Collection Data.xlsx", range = "A2:M96", sheet = "Professor Trash Wheel") %>% 
                   janitor::clean_names() %>% 
                   mutate(
                     sports_balls = 0,
                     sports_balls = as.integer(sports_balls)) %>% 
                   relocate(sports_balls, .after = chip_bags)
```

### add additional variable ‘trash_wheel_type’

After view the two datasets, I decide to use binding to combine mr.
trash wheel and professor_trash wheel. Since both datasets have variable
‘dumpster’, I decide to create variable ‘trash_wheel_type’ as the
identity variable.

``` r
mr_trash <- mutate(mr_trash, trash_wheel_type = "Mr")
professor_trash <- mutate(professor_trash, trash_wheel_type = "Professor")
```

### combine two dataset

``` r
trash_tidy <- bind_rows(mr_trash, professor_trash)
head(trash_tidy)
```

    ## # A tibble: 6 × 15
    ##   dumpster month  year date                weight_tons volume_…¹ plast…² polys…³
    ##      <dbl> <chr> <dbl> <dttm>                    <dbl>     <dbl>   <dbl>   <dbl>
    ## 1        1 May    2014 2014-05-16 00:00:00        4.31        18    1450    1820
    ## 2        2 May    2014 2014-05-16 00:00:00        2.74        13    1120    1030
    ## 3        3 May    2014 2014-05-16 00:00:00        3.45        15    2450    3100
    ## 4        4 May    2014 2014-05-17 00:00:00        3.1         15    2380    2730
    ## 5        5 May    2014 2014-05-17 00:00:00        4.06        18     980     870
    ## 6        6 May    2014 2014-05-20 00:00:00        2.71        13    1430    2140
    ## # … with 7 more variables: cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <int>,
    ## #   homes_powered <dbl>, trash_wheel_type <chr>, and abbreviated variable names
    ## #   ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

The combined dataset contain 641 rows and 15 columns. Among 15 columns,
the key variables are weight in tons and volume in cubic yards. The mean
weight of trash collect of the combined data is 3.0241498 tons. The mean
volume of trash collect of the combined data is 15.2199688 cubic yards.
The total weight of trash collected by Professor Trash Wheel = 190.12
tons. The total number of sports balls collected by Mr. Trash Wheel in
2020 is 856.

# Problem 3

### read and clean the data of pols-month.csv

``` r
pols_month <- read_csv("./data/pols-month.csv") %>% 
              janitor::clean_names() %>% 
              separate(mon, into = c("year", "month", "day"), sep = "-") %>% 
              mutate(
                year = as.integer(year),
                month = month.abb[as.integer(month)],
                day = as.integer(day),
                prez_gop = recode(prez_gop, `1` = "gop", `0` = "dem", `2` = "otherwise" ),
                prez_dem = recode(prez_dem, `1` = "dem", `0` = "gop")) %>% 
              pivot_longer(
                cols = c(prez_gop, prez_dem),
                names_to = NULL,
                values_to = "president") %>% 
              select(-contains("prez"), -day) %>% 
              distinct()
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### read and clean the data of snp.csv

``` r
snp <- read_csv("./data/snp.csv") %>%
       janitor::clean_names() %>% 
       separate(date, into = c("year", "month", "day"), sep = "/") %>% 
       mutate(
         year = as.integer(year),
         day = as.integer(day),
         month = as.integer(month),
         year_before_2001 = case_when(50 <= day & day <= 99 ~ 1900+day,
                                      day == 0 ~2000+day,
                                      1 <= day & day <= 49 ~ 0),
         
         month = case_when(year_before_2001 > 0 ~ year+0,
                           year_before_2001 == 0 ~ month+0),
         month = month.abb[month],
         
         year = case_when(year_before_2001 == 0 ~ 2000+year,
                          year_before_2001 > 0 ~ 0+year_before_2001)) %>% 
      select(-day,-year_before_2001)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(snp)
```

    ## # A tibble: 6 × 3
    ##    year month close
    ##   <dbl> <chr> <dbl>
    ## 1  2007 Jan   2080.
    ## 2  2006 Jan   2063.
    ## 3  2005 Jan   2107.
    ## 4  2004 Jan   2086.
    ## 5  2003 Feb   2068.
    ## 6  2002 Feb   2104.

I noticed the date in years after 2001(yyyy/mm/dd) is different from
date in years before 2001(mm/dd/yy).

I decide to create a new variable ‘year_before_2001’ used to seperate
years before 2001 and after 2001.

Then I mutate month for years before 2001(from mm/dd/yy to mm/mm/yy
since we do not need day so I just override it)

Next, I mutate years for years before 2001 based on the variable
‘year_before_2001’ (from mm/mm/yy to yyyy/mm/yy) and change years to 4
digit for years after 2001.

Finally, I drop the variable ‘day’ and variable ‘year_before_2001’ to
keep the columns I need.

### tidy the unemployment data

``` r
unemployment <- read_csv("./data/unemployment.csv") %>% 
                pivot_longer(
                  cols = Jan:Dec,
                  names_to = "month",
                  values_to = "percentage") %>% 
                janitor::clean_names()
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### join the dataset

``` r
fte_data <- left_join(pols_month, snp, by = c("year", "month") ) %>% 
left_join(unemployment, by = c("year", "month"))
head(fte_data)
```

    ## # A tibble: 6 × 11
    ##    year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##   <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ## 1  1947 Jan        23      51     253      23      45     198 dem          NA
    ## 2  1947 Feb        23      51     253      23      45     198 dem          NA
    ## 3  1947 Mar        23      51     253      23      45     198 dem          NA
    ## 4  1947 Apr        23      51     253      23      45     198 dem          NA
    ## 5  1947 May        23      51     253      23      45     198 dem          NA
    ## 6  1947 Jun        23      51     253      23      45     198 dem          NA
    ## # … with 1 more variable: percentage <dbl>

the data pols_month contain the number of national politicians who are
democratic or republican from 1947 to 2015. Data snp contain information
of closing value of stock market index from 1950 to 2012. Data
unemployment contain the information of percent of unemployment from
1948 to 2015. The combined data fte_data contain 965 rows and 11
columns. the range of years is from 1947 to 2015. The key variables is
president, close, and percentage.
